name: Deploy to Pantheon Master
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
    - name: Install PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: '8'
    - name: Installing Terminus
      if: steps.cache-terminus.outputs.cache-hit != 'true'
      run: |
        mkdir ~/terminus && cd ~/terminus
        git clone https://github.com/pantheon-systems/terminus.git
        chmod +x ~/terminus/terminus/bin/terminus
        composer -d ~/terminus/terminus install --no-dev
        ln -s ~/terminus/terminus/bin/terminus /usr/local/bin/terminus
    - run: |
        MACHINE_TOKEN=${{ secrets.PANTHEON_MACHINE_TOKEN }}
        terminus auth:login --machine-token=$MACHINE_TOKEN
        terminus self:config:dump
        terminus machine-token:list
