name: Deploy to Pantheon Master
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
    - name: Install PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: '8'
    - name: Installing Terminus
      if: steps.cache-terminus.outputs.cache-hit != 'true'
      run: |
        git clone https://github.com/pantheon-systems/terminus.git
        chmod +x terminus/bin/terminus
        composer --working-dir=terminus install --no-dev
        cd terminus && git checkout debug-print
    - run: |
        MACHINE_TOKEN=${{ secrets.PANTHEON_MACHINE_TOKEN }}
        terminus/bin/terminus auth:login --machine-token=$MACHINE_TOKEN
        terminus/bin/terminus self:config:dump
        terminus/bin/terminus machine-token:list
